resources:
  sle_source: http://147.2.207.237/repo/UNTESTED/SLE-12-SP1-Server-DVD-x86_64/
  ha_source: http://147.2.207.237/repo/UNTESTED/SLE-12-SP1-HA-DVD-x86_64/

nodes:
- name: node01
  disk: qcow2:/mnt/vm/sles_liub/sles12sp1-HA-node01.qcow2
  ostype: sles11
  vcpus: 2
  memory: 1024
  disk_size: 8192
  nic:
  graphics:
  
- name: node02
  disk: qcow2:/mnt/vm/sles_liub/sles12sp1-HA-node02.qcow2
  ostype: sles11
  vcpus: 2
  memory: 1024
  disk_size: 8192
  nic:
  graphics:

- name: node03
  disk: qcow2:/mnt/vm/sles_liub/sles12sp1-HA-node03.qcow2
  ostype: sles11
  vcpus: 2
  memory: 1024
  disk_size: 8192
  nic:
  graphics:

devices:
  disk_dir: /mnt/vm/sles_ha_auto/
  nic: br0

iscsi:
  target_ip: 147.2.207.237
  target_lun: iqn.2015-08.suse.bej.bliu:441a202b-6aa3-479f-b56f-374e2f38ba20
