#!/bin/bash

function isMaster()
{
    # Usage:
    #     isMaster <nodename>
    if [ $# -ne 1 ]
    then 
        return 1
    fi

    LOCALHOST=$(uname -n|cut -d "." -f 1)

    if [ "$1" == "$LOCALHOST" ]
    then
        #Master node
        return 0
    else
        return 1
    fi
}

function getSLEVersion()
{
    vals=`cat /etc/SuSE-release|grep -P "PATCHLEVEL|VERSION" | sed "s/ //g"`
    eval ${vals}
    echo SLE${VERSION}SP${PATCHLEVEL}
}

function nconvert()
{
    # Usage:
    #     result=`nconvert 3`
    echo -n $1 | tr "123456789" "bcdefghij"
}

function logit()
{
    # Usage:
    #     logit ls -l
    #     logit pwd >> output-file
    echo -e "== [`hostname`:${USER}@`pwd`]\nCommand: ${*}\nStart  : [`date`] \n`${*} 2>&1`\nStop   : [`date`]\n";
}

function getEnv()
{
    key=$1
    file="../cluster_conf"
    if [ $# -eq 2 ];then
        file=$2
    fi
    value=`grep $key $file|cut -d'=' -f2`
    echo $value
}

function get_hb_report()
{
    if [ $# -ne 2 ];then
        echo "usage: get_hb_report $CLUSTER_CONF $DIR_TO_PUT_FILE"
    fi
    cluster_conf=$1
    dest=$2
    #get the ip of 1st node, and try to run hb_report on it, then return to the jenkins server
    ip=`cat $cluster_conf | grep IP_NODE |cut -d "=" -f 2 | head -1`
    date_str=`date +%s`
    hb_report="hb_report_${ip}_${date_str}"
    ssh root@${ip} "systemctl restart pacemaker; sleep 3; hb_report -f 0:00 $hb_report"
    echo "ssh root@${ip}" "systemctl start pacemaker; sleep 3; hb_report -f 0:00 $hb_report"
    scp ${ip}:/root/$hb_report* $dest
}
