#!/bin/bash

function isMaster()
{
    # Usage:
    #     isMaster <nodename>
    if [ $# -ne 1 ]
    then 
        return 1
    fi

    LOCALHOST=$(uname -n|cut -d "." -f 1)

    if [ "$1" == "$LOCALHOST" ]
    then
        #Master node
        return 0
    else
        return 1
    fi
}

function getSLEVersion()
{
    vals=`cat /etc/SuSE-release|grep -P "PATCHLEVEL|VERSION" | sed "s/ //g"`
    eval ${vals}
    echo SLE${VERSION}SP${PATCHLEVEL}
}

function nconvert()
{
    # Usage:
    #     result=`nconvert 3`
    echo -n $1 | tr "123456789" "bcdefghij"
}

function logit()
{
    # Usage:
    #     logit ls -l
    #     logit pwd >> output-file
    echo -e "== [`hostname`:${USER}@`pwd`]\nCommand: ${*}\nStart  : [`date`] \n`${*} 2>&1`\nStop   : [`date`]\n";
}
